# Частота обновления NameTag'а и DisplayName (в тиках)
# Было сделано для обновления пинга и хп

# Ставьте 0 если хотите чтобы обновления нейм тега и.т.д не было
# (Нейм теги и.т.д будут обновлены при смене группы PurePerms, или же когда игрок только заходит на сервер) 
update: 20



# Что будет отображаться если игрок не состоит не в каком клане
clan-none: "..."



# Отключить ли цветные сообщения?
# Игроки не могут написать что-то с символом § в чат
antiColor-chat: true